params:  

  seed: ${...seed}

  algo:
    name: sac

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:
    mlp:
      units: [512, 256]
      activation: relu
      initializer:
        name: default

    log_std_bounds: [-5, 2]

  load_checkpoint: False
  load_path: nn/Humanoid_SAC.pth

  config:
    name: ${resolve_default:HumanoidSAC,${....experiment}}
    env_name: warp
    normalize_input: True
    reward_shaper:
      scale_value: 1
    max_epochs: ${resolve_default:5000,${....max_iterations}}
    num_steps_per_episode: 8
    save_best_after: 100
    save_frequency: 10000
    gamma: 0.99
    init_alpha: 1
    alpha_lr: 2e-4
    actor_lr: 3e-4
    critic_lr: 3e-4
    critic_tau: 5e-3
    batch_size: 2048
    learnable_temperature: True
    num_warmup_steps: 5 # total number of warmup steps: num_actors * num_steps_per_episode * num_warmup_steps
    replay_buffer_size: 1000000
    num_actors: 64