params:  

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512, 256]
      activation: swish
      d2rl: False
      
      initializer:
        name: default
      regularizer:
        name: None

  config:
    name: ${resolve_default:HumanoidPPO,${....experiment}}
    env_name: warp
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: ${resolve_default:500,${....max_iterations}}
    save_best_after: 200
    save_frequency: 100
    entropy_coef: 0.0
    truncate_grads: True
    grad_norm: 1.0
    e_clip: 0.2
    num_actors: 4096
    horizon_length: 32
    minibatch_size: 32768
    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_length: 8
    bounds_loss_coef: 0.0001
    
    player:
      determenistic: True
      games_num: 2
      num_actors: 2
      print_stats: True
